### ISSUE TITLE
Multiple Datasources using R2DBC does not work

### ISSUE THREAD

**Issue by charlie-harvey** [micronaut-projects/micronaut-r2dbc#46]
### Task List

- [ x] Steps to reproduce provided
- [ x] Stacktrace (if present) provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create two `r2dbc.datasources` (`dataSourceOne` and `dataSourceTwo`)
2. Annotate your Repository interface:
```
    @Repository(value = "dataSourceOne")
    @R2dbcRepository
```
3. Try to query things

### Expected Behaviour

Should be able to point a repository to a named datasource, but the @Named datasource is not actually getting created by the `DataR2dbcConfiguration` class

### Actual Behaviour

Query fails because the application does not know how to talk to the database.

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 2.2.2
- **Micronaut Data Version:** 2.2.1
- **Micronaut R2DBC Version:** 1.0.0.M2
- **JDK Version:** Corretto 11

### Example Application

- https://github.com/charlie-harvey/micronaut-r2dbc-multiple-datasources

**Comment by graemerocher** [comment]
I added a test for this and it is working fine https://github.com/micronaut-projects/micronaut-r2dbc/commit/cb58b17a4ffde41827316fd3a3e7042b5287f367#diff-accccf316133ff84c264b53d595a90f6068e0a8d182e420be46945ba4f9bd566

I believe your issue is because as with bean name you have to reference the kebab case name when referencing datasource names. You can see this is the logs:


```
11:24:34.041 [main] INFO  i.m.flyway.AbstractFlywayMigration - Running migrations for database with qualifier [data-source-one]
```

So `@Repository(value = "dataSourceOne")` should be `@Repository(value = "data-source-one")`

**Comment by charlie-harvey** [comment]
Thank you so much for taking the time to sort this out. Can't believe I blew so much time on that. Keep up the great work.
